#!/bin/bash

function act() {
	echo "source ~/.dotfile/main.vimrc" > ~/.vimrc
	echo "----- .vimrc updated. -----"

	echo "source ~/.dotfile/.zshrc" > ~/.zshrc
	echo "----- .zshrc updated. -----"

	echo "source ~/.dotfile/.tmux.conf" > ~/.tmux.conf
	echo "----- .tmux.conf updated. -----"
}

read -p "This may overwrite existing files in your home directory. Are you sure?  (y/n) " -n 1;	
echo "";	

if [[ $REPLY =~ ^[Yy]$ ]]; then			
	act;
else
	echo "----- terminated. -----"
fi;
