return {
  settings = {
    python = {
      analysis = {
        typeCheckingMode = "off",
      },
      -- so pyright can find the dependencies in the virtual environment
      -- `.venv` is generated by `uv sync` by default
      pythonPath = ".venv/bin/python",
    },
  },
}
